eureka:
  client:
    # 注册服务中心
    service-url:
      defaultZone: http://47.105.218.58:8761/eureka/,http://47.105.218.58:8762/eureka/,http://47.105.218.58:8763/eureka/
# 注册中心查看注册服务跳转链接地址：localhost => clientName
#  instance:
#    hostname: order
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#    instance-id: send-8401.com  # 在信息列表时显示主机名称
#    prefer-ip-address: true     # 访问的路径变为IP地址

# 必须是这个 bootstrap 配置才有效,特别注意 order.yml ,他是其他文件的通用配置
spring:
  application:
    name: order
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG-SERVER
      # 特别注意 order.yml ,他是其他文件的通用配置 order-dev.yml
      profile: dev
  # 配置链路监控地址
  zipkin:
    base-url: http://47.105.218.58:9411/
    sender:
      type: web # 坑的东西
  sleuth:
    sampler:
      probability: 1 # 默认只暴露 0.1 的数据请求,开发设置为1
    http:
      legacy:
        enabled: true
server:
  port: 8081


# 好像 feign 不起作用,对单独的 请求游泳
# hystrix的超时时间  (一般情况下 都是 ribbon 的超时时间（<）hystrix的超时时间（因为涉及到ribbon的重试机制） )
hystrix:
  command:
    # 默认匹配所有带有 @HystrixCommand 方法的注解，注意啊，这里是 default
    default:
      #      timeout: # 无效，不配置
      #        #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
      #        enabled: true
      execution:
        isolation:
          thread:
            # 如果配置ribbon的重试，hystrix的超时时间要大于ribbon的超时时间，ribbon才会重试
            # hystrix的超时时间=(1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout 比较好，具体看需求
            timeoutInMilliseconds: 16000 # 配置 hystrix 超时时间,方法注解中超时时间配置会覆盖掉默认配置。
    # 当ribbon超时后且hystrix没有超时，便会采取重试机制。当OkToRetryOnAllOperations设置为false时，只会对get请求进行重试。如果设置为true，
    # 便会对所有的请求进行重试，如果是put或post等写操作，如果服务器接口没做幂等性，会产生不好的结果，所以OkToRetryOnAllOperations慎用。
    # 为 listFor 方法 单独设置超时时间
    listFor:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 16000 # 配置 hystrix 超时时间,方法注解中超时时间配置会覆盖掉方法。

# feign 熔断措施，必须禁止 hystrix 配置
#feign:
#  hystrix:
#    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # 开放所有页面节点  默认只开启了health、info两个节点
        # 配置后监控路径为 http://localhost:8081/hystrix.stream,默认 http://localhost:8081/actuator/hystrix.stream
  #      base-path: /   # 修改访问路径  2.0之前默认是/   2.0默认是 /actuator  可以通过这个属性值修改
  server:
    port: 8081 #actuator端口
#    servlet: # 无效的配置
#      context-path: / # 同 base-path
logging:
  level:
    org.springframework.cloud.openfeign: debug
# 2.x 配置
feign:
  client:
    config:
      default:
        connectTimeout: 16000
        readTimeout: 26000
        loggerLevel: basic